apiVersion: v1
kind: Secret
metadata:
  name: logzio-metrics-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  logzio-metrics-shipping-token: {{ .Values.secrets.MetricsToken }}
  logzio-metrics-listener: {{ .Values.secrets.ListenerHost }}
  p8s-logzio-name: {{.Values.secrets.p8s_logzio_name}}

{{- if .Values.secrets.windowsNodeUsername }}
{{- if .Values.secrets.windowsNodePassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: logzio-windows-exporter-installer-secrets
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/basic-auth
stringData:
  username: {{.Values.secrets.windowsNodeUsername}}
  password: {{.Values.secrets.windowsNodePassword}}
{{- end }}
{{- end }}