apiVersion: {{ .Values.apiVersions.secret }}
kind: Secret
metadata:
  name: logzio-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  logzioURL: {{ required "Logz.io url is required!" .Values.secrets.logzioURL }}
  logzioToken: {{ required "Logz.io metrics token is required!" .Values.secrets.logzioToken }}