nameOverride: ""
fullnameOverride: ""

apiVersions:
  deployment: apps/v1
  configmap: v1
  secret: v1

namespace: default

replicaCount: 1

labels: {}

annotations: {}

customSpecs: {}

dotnetAppContainers:
  - name: dotnet-app
    image: mcr.microsoft.com/dotnet/core/samples:aspnetapp
    ports:
      - containerPort: 8000
    volumeMounts:
      - mountPath: /tmp
        name: diagnostics

logzioDotnetMonitor:
  name: logzio-dotnet-monitor
  image:
    name: logzio/logzio-dotnet-monitor
    tag: latest
  ports:
    - 52325

customVolumes: {}

customResources: {}

secrets:
  logzioURL: https://listener.logz.io:8053
  logzioToken: ""

configMap:
  dotnetMonitor: |
    {
      "GlobalCounter": {
        "IntervalSeconds": 5
      },
      "Metrics": {
        "Endpoints": "http://localhost:52325",
        "IncludeDefaultProviders": true,
        "MetricCount": 3,
        "Providers": [
          {
            "ProviderName": "Microsoft-AspNetCore-Server-Kestrel",
            "CounterNames": [
              "connections-per-second",
              "total-connections"
            ]
          }
        ]
      }
    }
  opentelemetry: |
    receivers:
      prometheus:
        config:
          scrape_configs:
            - job_name: 'dotnet-monitor-collector'
              scrape_interval: 15s
              static_configs:
                - targets: ['127.0.0.1:52325']
    exporters:
      prometheusremotewrite:
        endpoint: ${LOGZIO_URL}
        headers:
          Authorization: "Bearer ${LOGZIO_TOKEN}"
        external_labels:
    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          exporters: [prometheusremotewrite]
