
apiVersion: v1
kind: Secret
metadata:
  name: logzio-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  p8s-logzio-name: {{.Values.secrets.p8s_logzio_name}}
{{- if .Values.metrics.enabled }}
  logzio-metrics-shipping-token: {{ .Values.secrets.MetricsToken }}
  logzio-metrics-listener: {{ .Values.secrets.ListenerHost }}
{{- end }}
{{- if .Values.traces.enabled }}
  logzio-traces-shipping-token: {{ .Values.secrets.TracesToken }}
  logzio-listener-region: {{ .Values.secrets.LogzioRegion}}
{{- end }}
{{- if .Values.secrets.windowsNodeUsername }}
{{- if .Values.secrets.windowsNodePassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: logzio-windows-exporter-installer-secrets
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/basic-auth
stringData:
  username: {{.Values.secrets.windowsNodeUsername}}
  password: {{.Values.secrets.windowsNodePassword}}
{{- end }}
{{- end }}
